org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false
org.gradle.configuration-cache=true
org.gradle.java.installations.paths=C\:/Program Files/Java/Zulu-JDK-25,C\:/Program Files/Java/jdk-25

shadowjar_version=9.4.1

# Mod Info
mod_version=4.8.4207
mod_id=twilightforest
group_name=com.github.teamtwilight.twilightforest

# Minecraft
base_minecraft_version=26.2
minecraft_version=26.2

# NeoForge: https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.2.0.32-beta
mdg_version=2.0.141

# Deps
beanification_version=1.9.125
jei_version=30.13.0.84
rei_version=26.2.820
curios_version=16.0.0
top_version=1.21_neo-12.0.3-5

enable_tips_mod=false
