{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged",
    "module": "testframework",
    "version": "26.1.26w14a-herdcraft.24-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "testframework-26.1.26w14a-herdcraft.24-beta.jar",
          "url": "testframework-26.1.26w14a-herdcraft.24-beta.jar",
          "size": 547632,
          "sha512": "fc6e274650f82932d39081e08be4888a525884127559f8250133d12231d53b9e762a0741f583fa4a5c1e4585ff7b2aa3d5938561875c11969f81aed8e4cca471",
          "sha256": "ef2b9ae1c345605d80ca35776a67da330a6cae6086502a37add7b3a221f03802",
          "sha1": "b5a1e520e841c4c95f375ce1cbc52dcaee7bb756",
          "md5": "1982d76611ffc1a03d388be260efde9e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "testframework-26.1.26w14a-herdcraft.24-beta.jar",
          "url": "testframework-26.1.26w14a-herdcraft.24-beta.jar",
          "size": 547632,
          "sha512": "fc6e274650f82932d39081e08be4888a525884127559f8250133d12231d53b9e762a0741f583fa4a5c1e4585ff7b2aa3d5938561875c11969f81aed8e4cca471",
          "sha256": "ef2b9ae1c345605d80ca35776a67da330a6cae6086502a37add7b3a221f03802",
          "sha1": "b5a1e520e841c4c95f375ce1cbc52dcaee7bb756",
          "md5": "1982d76611ffc1a03d388be260efde9e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "testframework-26.1.26w14a-herdcraft.24-beta-sources.jar",
          "url": "testframework-26.1.26w14a-herdcraft.24-beta-sources.jar",
          "size": 356062,
          "sha512": "e71bc79835793fc1c010b711d9c65aeef239fa20b094636b9198f5ae801cf5600e8489249248f82a761ca1a060d673f67d72c77543b0a9790df07251ecce9fec",
          "sha256": "bc1407966fb51a189411ecdc713a1a1bb55815c5ccdbd82da61a589f26de2dc4",
          "sha1": "c7d4c5eebc5b685c1b008e5d9b30559f456768c8",
          "md5": "659f4d9c8bcfaf83cfe6698213be2ff6"
        }
      ]
    }
  ]
}
