package twilightforest.init;

import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.world.level.levelgen.feature.Feature;
import net.minecraft.world.level.levelgen.feature.configurations.*;
import twilightforest.TwilightForestMod;
import twilightforest.world.components.feature.*;
import twilightforest.world.components.feature.config.*;
import twilightforest.world.components.feature.templates.*;
import twilightforest.world.components.feature.trees.*;
import twilightforest.world.components.feature.trollcave.TrollBigMushgloomFeature;
import twilightforest.world.components.feature.trollcave.TrollHugeBrownMushroomFeature;
import twilightforest.world.components.feature.trollcave.TrollHugeRedMushroomFeature;

public class TFFeatures {

	public static final Feature<TFSmallLakeFeature.Configuration> SMALL_LAKE = new TFSmallLakeFeature(TFSmallLakeFeature.Configuration.CODEC);
	public static final Feature<HugeMushroomFeatureConfiguration> BIG_MUSHGLOOM = new BigMushgloomFeature(HugeMushroomFeatureConfiguration.CODEC);
	public static final Feature<HugeMushroomFeatureConfiguration> CANOPY_BROWN_MUSHROOM = new BrownCanopyMushroomFeature(HugeMushroomFeatureConfiguration.CODEC);
	public static final Feature<HugeMushroomFeatureConfiguration> CANOPY_RED_VANILLA_MUSHROOM = new RedCanopyMushroomFeature(HugeMushroomFeatureConfiguration.CODEC, 0);
	public static final Feature<HugeMushroomFeatureConfiguration> CANOPY_RED_SMOOTH_MUSHROOM = new RedCanopyMushroomFeature(HugeMushroomFeatureConfiguration.CODEC, 1);
	public static final Feature<HugeMushroomFeatureConfiguration> CANOPY_RED_SPHEROID_MUSHROOM = new RedCanopyMushroomFeature(HugeMushroomFeatureConfiguration.CODEC, 2);
	public static final Feature<HugeMushroomFeatureConfiguration> CANOPY_RED_FLAT_MUSHROOM = new RedCanopyMushroomFeature(HugeMushroomFeatureConfiguration.CODEC, 3);
	public static final Feature<TFTreeFeatureConfig> MEGA_OAK = new MegaOakTreeFeature(TFTreeFeatureConfig.codecTFTreeConfig);
	public static final Feature<TFTreeFeatureConfig> MEGA_CANOPY = new MegaCanopyTreeFeature(TFTreeFeatureConfig.codecTFTreeConfig);
	public static final Feature<NoneFeatureConfiguration> CAVE_STALACTITE = new BlockSpikeFeature(NoneFeatureConfiguration.CODEC);
	public static final Feature<TreeConfiguration> DARK_CANOPY_TREE = new DarkCanopyTreeFeature(TreeConfiguration.CODEC);
	public static final Feature<SwizzleConfig> DRUID_HUT = new DruidHutFeature(SwizzleConfig.CODEC);
	public static final Feature<NoneFeatureConfiguration> FALLEN_HOLLOW_LOG = new FallenHollowLogFeature(NoneFeatureConfiguration.CODEC);
	public static final Feature<NoneFeatureConfiguration> FALLEN_LEAVES = new FallenLeavesFeature(NoneFeatureConfiguration.CODEC);
	public static final Feature<HollowLogConfig> FALLEN_SMALL_LOG = new SmallFallenLogFeature(HollowLogConfig.CODEC);
	public static final Feature<BlockStateConfiguration> FIRE_JET = new FireJetFeature(BlockStateConfiguration.CODEC);
	public static final Feature<RuinedFoundationConfig> FOUNDATION = new FoundationFeature(RuinedFoundationConfig.CODEC);
	public static final Feature<NoneFeatureConfiguration> GRAVEYARD = new GraveyardFeature(NoneFeatureConfiguration.CODEC);
	public static final Feature<NoneFeatureConfiguration> GROVE_RUINS = new GroveRuinsFeature(NoneFeatureConfiguration.CODEC);
	public static final Feature<TFTreeFeatureConfig> HOLLOW_STUMP = new HollowStumpFeature(TFTreeFeatureConfig.codecTFTreeConfig);
	public static final Feature<NoneFeatureConfiguration> HUGE_LILY_PAD = new HugeLilypadFeature(NoneFeatureConfiguration.CODEC);
	public static final Feature<NoneFeatureConfiguration> HUGE_WATER_LILY = new HugeWaterLilyFeature(NoneFeatureConfiguration.CODEC);
	public static final Feature<BlockStateConfiguration> LAMPPOSTS = new LampostFeature(BlockStateConfiguration.CODEC);
	public static final Feature<TFTreeFeatureConfig> LARGE_WINTER_TREE = new LargeWinterTreeFeature(TFTreeFeatureConfig.codecTFTreeConfig);
	public static final Feature<TFTreeFeatureConfig> MINERS_TREE = new MiningTreeFeature(TFTreeFeatureConfig.codecTFTreeConfig);
	public static final Feature<NoneFeatureConfiguration> MONOLITH = new MonolithFeature(NoneFeatureConfiguration.CODEC);
	public static final Feature<DiskConfiguration> MYCELIUM_BLOB = new CheckAbovePatchFeature(DiskConfiguration.CODEC);
	public static final Feature<BerryBushConfig> BERRY_BUSH = new BerryBushFeature(BerryBushConfig.CODEC);
	public static final Feature<BlockStateConfiguration> UNDERGROUND_PLANTS = new UndergroundPlantFeature(BlockStateConfiguration.CODEC);
	public static final Feature<BlockStateConfiguration> UNDERGROUND_PLANTS_IN_STRUCTURE = new UndergroundPlantFeature(BlockStateConfiguration.CODEC, true);
	public static final Feature<BlockStateConfiguration> OREBERRY_BUSHES = new UndergroundPlantFeature(BlockStateConfiguration.CODEC, 1);
	public static final Feature<BlockStateConfiguration> TROLL_VINES = new UndergroundPlantFeature(BlockStateConfiguration.CODEC, true);
	public static final Feature<HugeMushroomFeatureConfiguration> TROLL_BIG_MUSHGLOOM = new TrollBigMushgloomFeature(HugeMushroomFeatureConfiguration.CODEC);
	public static final Feature<HugeMushroomFeatureConfiguration> TROLL_HUGE_RED_MUSHROOM = new TrollHugeRedMushroomFeature(HugeMushroomFeatureConfiguration.CODEC);
	public static final Feature<HugeMushroomFeatureConfiguration> TROLL_HUGE_BROWN_MUSHROOM = new TrollHugeBrownMushroomFeature(HugeMushroomFeatureConfiguration.CODEC);
	public static final Feature<NoneFeatureConfiguration> STONE_CIRCLE = new StoneCircleFeature(NoneFeatureConfiguration.CODEC);
	public static final Feature<ThornsConfig> THORNS = new ThornFeature(ThornsConfig.CODEC);
	public static final Feature<TFTreeFeatureConfig> TREE_OF_TIME = new TimeTreeFeature(TFTreeFeatureConfig.codecTFTreeConfig);
	public static final Feature<NoneFeatureConfiguration> WEBS = new WebFeature(NoneFeatureConfiguration.CODEC);
	public static final Feature<SwizzleConfig> SIMPLE_WELL = new SimpleWellFeature(SwizzleConfig.CODEC);
	public static final Feature<SwizzleConfig> FANCY_WELL = new FancyWellFeature(SwizzleConfig.CODEC);
	public static final Feature<RootConfig> WOOD_ROOTS = new WoodRootFeature(RootConfig.CODEC);
	public static final Feature<NoneFeatureConfiguration> SNOW_UNDER_TREES = new SnowUnderTreeFeature(NoneFeatureConfiguration.CODEC);
	public static final Feature<TreeConfiguration> SNOW_TREE = new SnowTreeFeature(TreeConfiguration.CODEC);
	public static final Feature<NoneFeatureConfiguration> ENCHANTED_FOREST_VINES = new EnchantedForestVinesFeature(NoneFeatureConfiguration.CODEC);
	public static final Feature<WeightedListFeatureConfig> WEIGHTED_LIST_SELECTOR = new WeightedListFeature(WeightedListFeatureConfig.CODEC);

	public static void init() {
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("small_lake"), SMALL_LAKE);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("big_mushgloom"), BIG_MUSHGLOOM);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("canopy_brown_mushroom"), CANOPY_BROWN_MUSHROOM);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("canopy_red_vanilla_mushroom"), CANOPY_RED_VANILLA_MUSHROOM);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("canopy_red_smooth_mushroom"), CANOPY_RED_SMOOTH_MUSHROOM);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("canopy_red_spheroid_mushroom"), CANOPY_RED_SPHEROID_MUSHROOM);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("canopy_red_flat_mushroom"), CANOPY_RED_FLAT_MUSHROOM);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("mega_oak"), MEGA_OAK);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("mega_canopy"), MEGA_CANOPY);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("block_spike"), CAVE_STALACTITE);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("dark_canopy_tree"), DARK_CANOPY_TREE);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("druid_hut"), DRUID_HUT);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("fallen_hollow_log"), FALLEN_HOLLOW_LOG);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("fallen_leaves"), FALLEN_LEAVES);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("fallen_small_log"), FALLEN_SMALL_LOG);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("fire_jet"), FIRE_JET);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("foundation"), FOUNDATION);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("graveyard"), GRAVEYARD);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("grove_ruins"), GROVE_RUINS);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("hollow_stump"), HOLLOW_STUMP);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("huge_lily_pad"), HUGE_LILY_PAD);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("huge_water_lily"), HUGE_WATER_LILY);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("lampposts"), LAMPPOSTS);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("large_winter_tree"), LARGE_WINTER_TREE);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("miners_tree"), MINERS_TREE);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("monolith"), MONOLITH);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("mycelium_blob"), MYCELIUM_BLOB);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("berry_bush"), BERRY_BUSH);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("underground_plants"), UNDERGROUND_PLANTS);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("underground_plants_in_structure"), UNDERGROUND_PLANTS_IN_STRUCTURE);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("oreberry_bushes"), OREBERRY_BUSHES);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("troll_vines"), TROLL_VINES);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("troll_cave_big_mushgloom"), TROLL_BIG_MUSHGLOOM);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("troll_cave_huge_red_mushroom"), TROLL_HUGE_RED_MUSHROOM);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("troll_cave_huge_brown_mushroom"), TROLL_HUGE_BROWN_MUSHROOM);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("stone_circle"), STONE_CIRCLE);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("thorns"), THORNS);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("tree_of_time"), TREE_OF_TIME);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("webs"), WEBS);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("simple_well"), SIMPLE_WELL);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("fancy_well"), FANCY_WELL);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("wood_roots"), WOOD_ROOTS);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("snow_under_trees"), SNOW_UNDER_TREES);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("anywhere_tree"), SNOW_TREE);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("enchanted_forest_vines"), ENCHANTED_FOREST_VINES);
		Registry.register(BuiltInRegistries.FEATURE, TwilightForestMod.prefix("weighted_list"), WEIGHTED_LIST_SELECTOR);
	}
}
