package twilightforest.init;

import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.world.level.levelgen.feature.Feature;
import twilightforest.TwilightForestMod;
import twilightforest.world.components.feature.*;
import twilightforest.world.components.feature.config.*;
import twilightforest.world.components.feature.templates.*;
import twilightforest.world.components.feature.trees.*;
import twilightforest.world.components.feature.trollcave.TrollBigMushgloomFeature;
import twilightforest.world.components.feature.trollcave.TrollHugeBrownMushroomFeature;
import twilightforest.world.components.feature.trollcave.TrollHugeRedMushroomFeature;

public class TFFeatures {

	public static final Feature SMALL_LAKE = new TFSmallLakeFeature() /* TODO-263: config via instance fields */;
	public static final Feature BIG_MUSHGLOOM = new BigMushgloomFeature() /* TODO-263: config via instance fields */;
	public static final Feature CANOPY_BROWN_MUSHROOM = new BrownCanopyMushroomFeature() /* TODO-263: config via instance fields */;
	public static final Feature CANOPY_RED_VANILLA_MUSHROOM = new RedCanopyMushroomFeature() /* TODO-263: config via instance fields */;
	public static final Feature CANOPY_RED_SMOOTH_MUSHROOM = new RedCanopyMushroomFeature() /* TODO-263: config via instance fields */;
	public static final Feature CANOPY_RED_SPHEROID_MUSHROOM = new RedCanopyMushroomFeature() /* TODO-263: config via instance fields */;
	public static final Feature CANOPY_RED_FLAT_MUSHROOM = new RedCanopyMushroomFeature() /* TODO-263: config via instance fields */;
	public static final Feature MEGA_OAK = new MegaOakTreeFeature() /* TODO-263: config via instance fields */;
	public static final Feature MEGA_CANOPY = new MegaCanopyTreeFeature() /* TODO-263: config via instance fields */;
	public static final Feature CAVE_STALACTITE = new BlockSpikeFeature() /* TODO-263: config via instance fields */;
	public static final Feature DARK_CANOPY_TREE = new DarkCanopyTreeFeature() /* TODO-263: config via instance fields */;
	public static final Feature DRUID_HUT = new DruidHutFeature() /* TODO-263: config via instance fields */;
	public static final Feature FALLEN_HOLLOW_LOG = new FallenHollowLogFeature() /* TODO-263: config via instance fields */;
	public static final Feature FALLEN_LEAVES = new FallenLeavesFeature() /* TODO-263: config via instance fields */;
	public static final Feature FALLEN_SMALL_LOG = new SmallFallenLogFeature() /* TODO-263: config via instance fields */;
	public static final Feature FIRE_JET = new FireJetFeature() /* TODO-263: config via instance fields */;
	public static final Feature FOUNDATION = new FoundationFeature() /* TODO-263: config via instance fields */;
	public static final Feature GRAVEYARD = new GraveyardFeature() /* TODO-263: config via instance fields */;
	public static final Feature GROVE_RUINS = new GroveRuinsFeature() /* TODO-263: config via instance fields */;
	public static final Feature HOLLOW_STUMP = new HollowStumpFeature() /* TODO-263: config via instance fields */;
	public static final Feature HUGE_LILY_PAD = new HugeLilypadFeature() /* TODO-263: config via instance fields */;
	public static final Feature HUGE_WATER_LILY = new HugeWaterLilyFeature() /* TODO-263: config via instance fields */;
	public static final Feature LAMPPOSTS = new LampostFeature() /* TODO-263: config via instance fields */;
	public static final Feature LARGE_WINTER_TREE = new LargeWinterTreeFeature() /* TODO-263: config via instance fields */;
	public static final Feature MINERS_TREE = new MiningTreeFeature() /* TODO-263: config via instance fields */;
	public static final Feature MONOLITH = new MonolithFeature() /* TODO-263: config via instance fields */;
	public static final Feature MYCELIUM_BLOB = new CheckAbovePatchFeature() /* TODO-263: config via instance fields */;
	public static final Feature BERRY_BUSH = new BerryBushFeature() /* TODO-263: config via instance fields */;
	public static final Feature UNDERGROUND_PLANTS = new UndergroundPlantFeature() /* TODO-263: config via instance fields */;
	public static final Feature UNDERGROUND_PLANTS_IN_STRUCTURE = new UndergroundPlantFeature() /* TODO-263: config via instance fields */;
	public static final Feature OREBERRY_BUSHES = new UndergroundPlantFeature() /* TODO-263: config via instance fields */;
	public static final Feature TROLL_VINES = new UndergroundPlantFeature() /* TODO-263: config via instance fields */;
	public static final Feature TROLL_BIG_MUSHGLOOM = new TrollBigMushgloomFeature() /* TODO-263: config via instance fields */;
	public static final Feature TROLL_HUGE_RED_MUSHROOM = new TrollHugeRedMushroomFeature() /* TODO-263: config via instance fields */;
	public static final Feature TROLL_HUGE_BROWN_MUSHROOM = new TrollHugeBrownMushroomFeature() /* TODO-263: config via instance fields */;
	public static final Feature STONE_CIRCLE = new StoneCircleFeature() /* TODO-263: config via instance fields */;
	public static final Feature THORNS = new ThornFeature() /* TODO-263: config via instance fields */;
	public static final Feature TREE_OF_TIME = new TimeTreeFeature() /* TODO-263: config via instance fields */;
	public static final Feature WEBS = new WebFeature() /* TODO-263: config via instance fields */;
	public static final Feature SIMPLE_WELL = new SimpleWellFeature() /* TODO-263: config via instance fields */;
	public static final Feature FANCY_WELL = new FancyWellFeature() /* TODO-263: config via instance fields */;
	public static final Feature WOOD_ROOTS = new WoodRootFeature() /* TODO-263: config via instance fields */;
	public static final Feature SNOW_UNDER_TREES = new SnowUnderTreeFeature() /* TODO-263: config via instance fields */;
	public static final Feature SNOW_TREE = new SnowTreeFeature() /* TODO-263: config via instance fields */;
	public static final Feature ENCHANTED_FOREST_VINES = new EnchantedForestVinesFeature() /* TODO-263: config via instance fields */;
	public static final Feature WEIGHTED_LIST_SELECTOR = new WeightedListFeature() /* TODO-263: config via instance fields */;

		public static void init() {
		// 26.3: feature types are registered as MapCodecs into BuiltInRegistries.FEATURE_TYPE
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("small_lake"), SMALL_LAKE.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("big_mushgloom"), BIG_MUSHGLOOM.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("canopy_brown_mushroom"), CANOPY_BROWN_MUSHROOM.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("canopy_red_vanilla_mushroom"), CANOPY_RED_VANILLA_MUSHROOM.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("canopy_red_smooth_mushroom"), CANOPY_RED_SMOOTH_MUSHROOM.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("canopy_red_spheroid_mushroom"), CANOPY_RED_SPHEROID_MUSHROOM.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("canopy_red_flat_mushroom"), CANOPY_RED_FLAT_MUSHROOM.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("mega_oak"), MEGA_OAK.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("mega_canopy"), MEGA_CANOPY.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("block_spike"), CAVE_STALACTITE.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("dark_canopy_tree"), DARK_CANOPY_TREE.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("druid_hut"), DRUID_HUT.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("fallen_hollow_log"), FALLEN_HOLLOW_LOG.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("fallen_leaves"), FALLEN_LEAVES.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("fallen_small_log"), FALLEN_SMALL_LOG.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("fire_jet"), FIRE_JET.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("foundation"), FOUNDATION.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("graveyard"), GRAVEYARD.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("grove_ruins"), GROVE_RUINS.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("hollow_stump"), HOLLOW_STUMP.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("huge_lily_pad"), HUGE_LILY_PAD.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("huge_water_lily"), HUGE_WATER_LILY.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("lampposts"), LAMPPOSTS.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("large_winter_tree"), LARGE_WINTER_TREE.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("miners_tree"), MINERS_TREE.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("monolith"), MONOLITH.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("mycelium_blob"), MYCELIUM_BLOB.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("berry_bush"), BERRY_BUSH.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("underground_plants"), UNDERGROUND_PLANTS.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("underground_plants_in_structure"), UNDERGROUND_PLANTS_IN_STRUCTURE.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("oreberry_bushes"), OREBERRY_BUSHES.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("troll_vines"), TROLL_VINES.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("troll_cave_big_mushgloom"), TROLL_BIG_MUSHGLOOM.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("troll_cave_huge_red_mushroom"), TROLL_HUGE_RED_MUSHROOM.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("troll_cave_huge_brown_mushroom"), TROLL_HUGE_BROWN_MUSHROOM.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("stone_circle"), STONE_CIRCLE.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("thorns"), THORNS.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("tree_of_time"), TREE_OF_TIME.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("webs"), WEBS.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("simple_well"), SIMPLE_WELL.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("fancy_well"), FANCY_WELL.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("wood_roots"), WOOD_ROOTS.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("snow_under_trees"), SNOW_UNDER_TREES.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("anywhere_tree"), SNOW_TREE.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("enchanted_forest_vines"), ENCHANTED_FOREST_VINES.codec());
		Registry.register(BuiltInRegistries.FEATURE_TYPE, TwilightForestMod.prefix("weighted_list"), WEIGHTED_LIST_SELECTOR.codec());
	}
}
