package twilightforest.init;

import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.sounds.SoundEvent;
import twilightforest.TwilightForestMod;

public final class TFSounds {

	public static final SoundEvent ACID_RAIN_BURNS = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("environment.twilightforest.acid_rain"));
	public static final SoundEvent ALPHA_YETI_ALERT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.alpha_yeti.alert"));
	public static final SoundEvent ALPHA_YETI_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.alpha_yeti.death"));
	public static final SoundEvent ALPHA_YETI_GRAB = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.alpha_yeti.grab"));
	public static final SoundEvent ALPHA_YETI_GROWL = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.alpha_yeti.growl"));
	public static final SoundEvent ALPHA_YETI_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.alpha_yeti.hurt"));
	public static final SoundEvent ALPHA_YETI_ICE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.alpha_yeti.ice"));
	public static final SoundEvent ALPHA_YETI_PANT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.alpha_yeti.pant"));
	public static final SoundEvent ALPHA_YETI_ROAR = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.alpha_yeti.roar"));
	public static final SoundEvent ALPHA_YETI_THROW = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.alpha_yeti.throw"));
	public static final SoundEvent BEANSTALK_GROWTH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.beanstalk.grow"));
	public static final SoundEvent BIGHORN_SHEEP_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.bighorn_sheep.ambient"));
	public static final SoundEvent BIGHORN_SHEEP_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.bighorn_sheep.death"));
	public static final SoundEvent BIGHORN_SHEEP_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.bighorn_sheep.hurt"));
	public static final SoundEvent BIGHORN_SHEEP_STEP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.bighorn_sheep.step"));
	public static final SoundEvent BLOCKCHAIN_GOBLIN_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.blockchain_goblin.ambient"));
	public static final SoundEvent BLOCKCHAIN_GOBLIN_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.blockchain_goblin.death"));
	public static final SoundEvent BLOCKCHAIN_GOBLIN_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.blockchain_goblin.hurt"));
	public static final SoundEvent BLOCK_AND_CHAIN_COLLIDE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.block_and_chain.collide"));
	public static final SoundEvent BLOCK_AND_CHAIN_FIRED = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.block_and_chain.fire"));
	public static final SoundEvent BLOCK_AND_CHAIN_HIT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.block_and_chain.hit"));
	public static final SoundEvent BLOCK_ANNIHILATED = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.generic.annihilation"));
	public static final SoundEvent BOAR_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.boar.ambient"));
	public static final SoundEvent BOAR_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.boar.death"));
	public static final SoundEvent BOAR_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.boar.hurt"));
	public static final SoundEvent BOAR_STEP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.boar.step"));
	public static final SoundEvent BOOKSHELF_CONVERTS = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.chiseled_bookshelf.convert"));
	public static final SoundEvent BOSS_CHEST_APPEAR = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.boss_chest.appear"));
	public static final SoundEvent BRITTLE_FLASK_BREAK = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.flask.break"));
	public static final SoundEvent BRITTLE_FLASK_CRACK = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.flask.crack"));
	public static final SoundEvent BUG_SQUISH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.bug.squish"));
	public static final SoundEvent BUILDER_CREATE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.builder.create"));
	public static final SoundEvent BUILDER_OFF = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.builder.off"));
	public static final SoundEvent BUILDER_ON = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.builder.on"));
	public static final SoundEvent BUILDER_REPLACE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.builder.replace"));
	public static final SoundEvent CANDELABRA_LIGHT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.candelabra.light"));
	public static final SoundEvent CANDELABRA_OMINOUS = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.candelabra.ominous"));
	public static final SoundEvent CARMINITE_BROODLING_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.carminite_broodling.ambient"));
	public static final SoundEvent CARMINITE_BROODLING_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.carminite_broodling.death"));
	public static final SoundEvent CARMINITE_BROODLING_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.carminite_broodling.hurt"));
	public static final SoundEvent CARMINITE_BROODLING_STEP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.carminite_broodling.step"));
	public static final SoundEvent CARMINITE_GHASTGUARD_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.carminite_ghastguard.ambient"));
	public static final SoundEvent CARMINITE_GHASTGUARD_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.carminite_ghastguard.death"));
	public static final SoundEvent CARMINITE_GHASTGUARD_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.carminite_ghastguard.hurt"));
	public static final SoundEvent CARMINITE_GHASTGUARD_SHOOT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.carminite_ghastguard.shoot"));
	public static final SoundEvent CARMINITE_GHASTGUARD_WARN = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.carminite_ghastguard.warn"));
	public static final SoundEvent CARMINITE_GHASTLING_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.carminite_ghastling.ambient"));
	public static final SoundEvent CARMINITE_GHASTLING_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.carminite_ghastling.death"));
	public static final SoundEvent CARMINITE_GHASTLING_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.carminite_ghastling.hurt"));
	public static final SoundEvent CARMINITE_GHASTLING_SHOOT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.carminite_ghastling.shoot"));
	public static final SoundEvent CARMINITE_GHASTLING_WARN = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.carminite_ghastling.warn"));
	public static final SoundEvent CARMINITE_GOLEM_ATTACK = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.carminite_golem.attack"));
	public static final SoundEvent CARMINITE_GOLEM_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.carminite_golem.death"));
	public static final SoundEvent CARMINITE_GOLEM_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.carminite_golem.hurt"));
	public static final SoundEvent CARMINITE_GOLEM_STEP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.carminite_golem.step"));
	public static final SoundEvent CASKET_CLOSE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.casket.close"));
	public static final SoundEvent CASKET_LOCKED = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.casket.locked"));
	public static final SoundEvent CASKET_OPEN = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.casket.open"));
	public static final SoundEvent CASKET_REPAIR = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.casket.repair"));
	public static final SoundEvent CHARM_KEEP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.charm.keep"));
	public static final SoundEvent CHARM_LIFE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.charm.life"));
	public static final SoundEvent CICADA = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.cicada"));
	public static final SoundEvent CYCLE_MAPS = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.travellers_gear.cycle_maps"));
	public static final SoundEvent CYCLE_MAPS_EMPTY = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.travellers_gear.cycle_maps_empty"));
	public static final SoundEvent DEATH_TOME_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.death_tome.ambient"));
	public static final SoundEvent DEATH_TOME_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.death_tome.death"));
	public static final SoundEvent DEATH_TOME_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.death_tome.hurt"));
	public static final SoundEvent DEER_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.deer.ambient"));
	public static final SoundEvent DEER_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.deer.death"));
	public static final SoundEvent DEER_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.deer.hurt"));
	public static final SoundEvent DEER_EAT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.deer.eat"));
	public static final SoundEvent DOOR_ACTIVATED = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.door.activate"));
	public static final SoundEvent DOOR_REAPPEAR = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.door.reappear"));
	public static final SoundEvent DOOR_VANISH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.door.vanish"));
	public static final SoundEvent DOUBLE_JUMP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.travellers_gear.double_jump"));
	public static final SoundEvent DRYING_RACK_ADD_ITEM = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.drying_rack.add_item"));
	public static final SoundEvent DRYING_RACK_REMOVE_ITEM = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.drying_rack.remove_item"));
	public static final SoundEvent DWARF_RABBIT_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.dwarf_rabbit.ambient"));
	public static final SoundEvent DWARF_RABBIT_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.dwarf_rabbit.death"));
	public static final SoundEvent DWARF_RABBIT_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.dwarf_rabbit.hurt"));
	public static final SoundEvent FAN_WHOOSH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.fan.whoosh"));
	public static final SoundEvent FIRE_BEETLE_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.fire_beetle.ambient"));
	public static final SoundEvent FIRE_BEETLE_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.fire_beetle.death"));
	public static final SoundEvent FIRE_BEETLE_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.fire_beetle.hurt"));
	public static final SoundEvent FIRE_BEETLE_SHOOT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.fire_beetle.shoot"));
	public static final SoundEvent FIRE_BEETLE_STEP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.fire_beetle.step"));
	public static final SoundEvent FLASK_FILL = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.flask.fill"));
	public static final SoundEvent GHAST_TRAP_ACTIVE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.ghast_trap.active"));
	public static final SoundEvent GHAST_TRAP_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.ghast_trap.ambient"));
	public static final SoundEvent GHAST_TRAP_ON = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.ghast_trap.on"));
	public static final SoundEvent GHAST_TRAP_SPINDOWN = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.ghast_trap.spindown"));
	public static final SoundEvent GHAST_TRAP_WARMUP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.ghast_trap.warmup"));
	public static final SoundEvent GLASS_SWORD_BREAK = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.glass_sword.break"));
	public static final SoundEvent GOBLIN_KNIGHT_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.goblin_knight.ambient"));
	public static final SoundEvent GOBLIN_KNIGHT_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.goblin_knight.death"));
	public static final SoundEvent GOBLIN_KNIGHT_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.goblin_knight.hurt"));
	public static final SoundEvent GOBLIN_KNIGHT_MUFFLED_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.goblin_knight.muffled.ambient"));
	public static final SoundEvent GOBLIN_KNIGHT_MUFFLED_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.goblin_knight.muffled.death"));
	public static final SoundEvent GOBLIN_KNIGHT_MUFFLED_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.goblin_knight.muffled.hurt"));
	public static final SoundEvent GOGGLES_ZOOM_IN = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.travellers_goggles.zoom_in"));
	public static final SoundEvent GOGGLES_ZOOM_OUT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.travellers_goggles.zoom_out"));
	public static final SoundEvent HEDGE_SPIDER_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.hedge_spider.ambient"));
	public static final SoundEvent HEDGE_SPIDER_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.hedge_spider.death"));
	public static final SoundEvent HEDGE_SPIDER_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.hedge_spider.hurt"));
	public static final SoundEvent HEDGE_SPIDER_STEP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.hedge_spider.step"));
	public static final SoundEvent HELMET_CRAB_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.helmet_crab.ambient"));
	public static final SoundEvent HELMET_CRAB_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.helmet_crab.death"));
	public static final SoundEvent HELMET_CRAB_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.helmet_crab.hurt"));
	public static final SoundEvent HELMET_CRAB_STEP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.helmet_crab.step"));
	public static final SoundEvent HOSTILE_WOLF_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.hostile_wolf.ambient"));
	public static final SoundEvent HOSTILE_WOLF_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.hostile_wolf.death"));
	public static final SoundEvent HOSTILE_WOLF_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.hostile_wolf.hurt"));
	public static final SoundEvent HOSTILE_WOLF_TARGET = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.hostile_wolf.target"));
	public static final SoundEvent HYDRA_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.hydra.death"));
	public static final SoundEvent HYDRA_GROWL = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.hydra.growl"));
	public static final SoundEvent HYDRA_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.hydra.hurt"));
	public static final SoundEvent HYDRA_ROAR = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.hydra.roar"));
	public static final SoundEvent HYDRA_SHOOT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.hydra.shoot"));
	public static final SoundEvent HYDRA_SHOOT_FIRE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.hydra.shoot_fire"));
	public static final SoundEvent HYDRA_WARN = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.hydra.warn"));
	public static final SoundEvent ICE_BOMB_FIRED = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.ice_bomb.fired"));
	public static final SoundEvent ICE_CORE_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.ice.ambient"));
	public static final SoundEvent ICE_CORE_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.ice.death"));
	public static final SoundEvent ICE_CORE_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.ice.hurt"));
	public static final SoundEvent ICE_CORE_SHOOT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.ice.shoot"));
	public static final SoundEvent JET_ACTIVE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.jet.active"));
	public static final SoundEvent JET_POP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.jet.pop"));
	public static final SoundEvent JET_START = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.jet.start"));
	public static final SoundEvent KING_SPIDER_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.king_spider.ambient"));
	public static final SoundEvent KING_SPIDER_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.king_spider.death"));
	public static final SoundEvent KING_SPIDER_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.king_spider.hurt"));
	public static final SoundEvent KING_SPIDER_STEP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.king_spider.step"));
	public static final SoundEvent KNIGHTMETAL_EQUIP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.knightmetal_armor.equip"));
	public static final SoundEvent KNIGHT_PHANTOM_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.knight_phantom.ambient"));
	public static final SoundEvent KNIGHT_PHANTOM_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.knight_phantom.death"));
	public static final SoundEvent KNIGHT_PHANTOM_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.knight_phantom.hurt"));
	public static final SoundEvent KNIGHT_PHANTOM_THROW_AXE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.knight_phantom.axe"));
	public static final SoundEvent KNIGHT_PHANTOM_THROW_PICK = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.knight_phantom.pickaxe"));
	public static final SoundEvent KOBOLD_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.kobold.ambient"));
	public static final SoundEvent KOBOLD_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.kobold.death"));
	public static final SoundEvent KOBOLD_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.kobold.hurt"));
	public static final SoundEvent KOBOLD_MUNCH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.kobold.munch"));
	public static final SoundEvent LAMP_BURN = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.lamp.burn"));
	public static final SoundEvent LICH_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.lich.ambient"));
	public static final SoundEvent LICH_CLONE_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.lich_clone.hurt"));
	public static final SoundEvent LICH_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.lich.death"));
	public static final SoundEvent LICH_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.lich.hurt"));
	public static final SoundEvent LICH_POP_MOB = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.lich.pop_mob"));
	public static final SoundEvent LICH_SHOOT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.lich.shoot"));
	public static final SoundEvent LICH_TELEPORT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.lich.teleport"));
	public static final SoundEvent LIFE_SCEPTER_DRAIN = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.life_scepter.drain"));
	public static final SoundEvent LOCKED_VANISHING_BLOCK = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.vanish.locked"));
	public static final SoundEvent LOYAL_ZOMBIE_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.loyal_zombie.ambient"));
	public static final SoundEvent LOYAL_ZOMBIE_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.loyal_zombie.death"));
	public static final SoundEvent LOYAL_ZOMBIE_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.loyal_zombie.hurt"));
	public static final SoundEvent LOYAL_ZOMBIE_STEP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.loyal_zombie.step"));
	public static final SoundEvent MAGNET_GRAB = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.magnet.grab"));
	public static final SoundEvent MAZE_SLIME_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.maze_slime.death"));
	public static final SoundEvent MAZE_SLIME_DEATH_SMALL = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.maze_slime_small.death"));
	public static final SoundEvent MAZE_SLIME_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.maze_slime.hurt"));
	public static final SoundEvent MAZE_SLIME_HURT_SMALL = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.maze_slime_small.hurt"));
	public static final SoundEvent MAZE_SLIME_SQUISH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.maze_slime.squish"));
	public static final SoundEvent MAZE_SLIME_SQUISH_SMALL = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.maze_slime_small.squish"));
	public static final SoundEvent METAL_SHIELD_SHATTERS = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.knightmetal_shield.shatter"));
	public static final SoundEvent MINION_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.minion.ambient"));
	public static final SoundEvent MINION_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.minion.death"));
	public static final SoundEvent MINION_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.minion.hurt"));
	public static final SoundEvent MINION_STEP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.minion.step"));
	public static final SoundEvent MINION_SUMMON = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.minion.summon"));
	public static final SoundEvent MINOSHROOM_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.minoshroom.ambient"));
	public static final SoundEvent MINOSHROOM_ATTACK = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.minoshroom.attack"));
	public static final SoundEvent MINOSHROOM_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.minoshroom.death"));
	public static final SoundEvent MINOSHROOM_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.minoshroom.hurt"));
	public static final SoundEvent MINOSHROOM_SLAM = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.minoshroom.slam"));
	public static final SoundEvent MINOSHROOM_STEP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.minoshroom.step"));
	public static final SoundEvent MINOTAUR_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.minotaur.ambient"));
	public static final SoundEvent MINOTAUR_ATTACK = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.minotaur.attack"));
	public static final SoundEvent MINOTAUR_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.minotaur.death"));
	public static final SoundEvent MINOTAUR_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.minotaur.hurt"));
	public static final SoundEvent MINOTAUR_STEP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.minotaur.step"));
	public static final SoundEvent MIST_WOLF_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.mist_wolf.ambient"));
	public static final SoundEvent MIST_WOLF_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.mist_wolf.death"));
	public static final SoundEvent MIST_WOLF_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.mist_wolf.hurt"));
	public static final SoundEvent MIST_WOLF_TARGET = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.mist_wolf.target"));
	public static final SoundEvent MOONWORM_SQUISH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.moonworm.squish"));
	public static final SoundEvent MOSQUITO = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.mosquito.ambient"));
	public static final SoundEvent NAGA_HISS = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.naga.hiss"));
	public static final SoundEvent NAGA_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.naga.hurt"));
	public static final SoundEvent NAGA_RATTLE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.naga.rattle"));
	public static final SoundEvent ORE_METER_CLEAR = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.ore_meter.clear"));
	public static final SoundEvent ORE_METER_CRACKLE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.ore_meter.crackle"));
	public static final SoundEvent ORE_METER_TARGET_BLOCK = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.ore_meter.target_block"));
	public static final SoundEvent PEDESTAL_ACTIVATE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.trophy_pedestal.activate"));
	public static final SoundEvent PENGUIN_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.penguin.ambient"));
	public static final SoundEvent PENGUIN_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.penguin.death"));
	public static final SoundEvent PENGUIN_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.penguin.hurt"));
	public static final SoundEvent PERFECT_DODGE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.travellers_gear.perfect_dodge"));
	public static final SoundEvent PICKED_TORCHBERRIES = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.torchberry.harvest"));
	public static final SoundEvent PINCH_BEETLE_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.pinch_beetle.ambient"));
	public static final SoundEvent PINCH_BEETLE_ATTACK = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.pinch_beetle.attack"));
	public static final SoundEvent PINCH_BEETLE_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.pinch_beetle.death"));
	public static final SoundEvent PINCH_BEETLE_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.pinch_beetle.hurt"));
	public static final SoundEvent PINCH_BEETLE_STEP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.pinch_beetle.step"));
	public static final SoundEvent PORTAL_WHOOSH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.portal.whoosh"));
	public static final SoundEvent POWDER_USE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.transformation_powder.use"));
	public static final SoundEvent QUEST_RAM_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.quest_ram.ambient"));
	public static final SoundEvent QUEST_RAM_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.quest_ram.death"));
	public static final SoundEvent QUEST_RAM_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.quest_ram.hurt"));
	public static final SoundEvent QUEST_RAM_STEP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.quest_ram.step"));
	public static final SoundEvent RAVEN_CAW = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.raven.caw"));
	public static final SoundEvent RAVEN_SQUAWK = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.raven.squawk"));
	public static final SoundEvent REACTOR_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.reactor.ambient"));
	public static final SoundEvent REAPPEAR_BLOCK = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.reappearing_block.reappear"));
	public static final SoundEvent REAPPEAR_POOF = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.reappearing_block.vanish"));
	public static final SoundEvent REDCAP_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.redcap.ambient"));
	public static final SoundEvent REDCAP_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.redcap.death"));
	public static final SoundEvent REDCAP_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.redcap.hurt"));
	public static final SoundEvent SHIELD_ADD = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.fortification_shield.add"));
	public static final SoundEvent SHIELD_BLOCK = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.fortification_shield.block"));
	public static final SoundEvent SHIELD_BREAK = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.fortification_shield.break"));
	public static final SoundEvent SHIELD_EXPIRE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.fortification_shield.expire"));
	public static final SoundEvent SIDE_STEP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.travellers_gear.side_step"));
	public static final SoundEvent SIDE_STEP_CHARGED = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.travellers_gear.side_step_ready"));
	public static final SoundEvent SKELETON_DRUID_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.skeleton_druid.ambient"));
	public static final SoundEvent SKELETON_DRUID_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.skeleton_druid.death"));
	public static final SoundEvent SKELETON_DRUID_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.skeleton_druid.hurt"));
	public static final SoundEvent SKELETON_DRUID_SHOOT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.skeleton_druid.shoot"));
	public static final SoundEvent SKELETON_DRUID_STEP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.skeleton_druid.step"));
	public static final SoundEvent SKULL_CHEST_CLOSE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.skull_chest.close"));
	public static final SoundEvent SKULL_CHEST_LOCKED = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.skull_chest.locked"));
	public static final SoundEvent SKULL_CHEST_OPEN = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.skull_chest.open"));
	public static final SoundEvent SLIDER = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.slider.move"));
	public static final SoundEvent SLIME_BEETLE_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.slime_beetle.ambient"));
	public static final SoundEvent SLIME_BEETLE_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.slime_beetle.death"));
	public static final SoundEvent SLIME_BEETLE_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.slime_beetle.hurt"));
	public static final SoundEvent SLIME_BEETLE_SQUISH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.slime_beetle.squish"));
	public static final SoundEvent SLIME_BEETLE_STEP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.slime_beetle.step"));
	public static final SoundEvent SMOKER_START = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.smoker.start"));
	public static final SoundEvent SNOW_GUARDIAN_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.snow_guardian.ambient"));
	public static final SoundEvent SNOW_GUARDIAN_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.snow_guardian.death"));
	public static final SoundEvent SNOW_GUARDIAN_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.snow_guardian.hurt"));
	public static final SoundEvent SNOW_QUEEN_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.snow_queen.ambient"));
	public static final SoundEvent SNOW_QUEEN_ATTACK = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.snow_queen.attack"));
	public static final SoundEvent SNOW_QUEEN_BREAK = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.snow_queen.break"));
	public static final SoundEvent SNOW_QUEEN_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.snow_queen.death"));
	public static final SoundEvent SNOW_QUEEN_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.snow_queen.hurt"));
	public static final SoundEvent SQUIRREL_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.squirrel.ambient"));
	public static final SoundEvent SQUIRREL_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.squirrel.death"));
	public static final SoundEvent SQUIRREL_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.squirrel.hurt"));
	public static final SoundEvent SWAP_HOTBAR = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.travellers_gear.swap_hotbar"));
	public static final SoundEvent SWARM_SPIDER_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.swarm_spider.ambient"));
	public static final SoundEvent SWARM_SPIDER_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.swarm_spider.death"));
	public static final SoundEvent SWARM_SPIDER_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.swarm_spider.hurt"));
	public static final SoundEvent SWARM_SPIDER_STEP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.swarm_spider.step"));
	public static final SoundEvent TEAR_BREAK = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.tear.break"));
	public static final SoundEvent TIME_CORE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.core.time"));
	public static final SoundEvent TINY_BIRD_CHIRP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.tiny_bird.chirp"));
	public static final SoundEvent TINY_BIRD_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.tiny_bird.hurt"));
	public static final SoundEvent TINY_BIRD_SONG = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.tiny_bird.song"));
	public static final SoundEvent TINY_BIRD_TAKEOFF = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.tiny_bird.takeoff"));
	public static final SoundEvent TOWERWOOD_BORER_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.towerwood_borer.ambient"));
	public static final SoundEvent TOWERWOOD_BORER_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.towerwood_borer.death"));
	public static final SoundEvent TOWERWOOD_BORER_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.towerwood_borer.hurt"));
	public static final SoundEvent TOWERWOOD_BORER_STEP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.towerwood_borer.step"));
	public static final SoundEvent TRANSFORMATION_CORE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.core.transformation"));
	public static final SoundEvent TROLL_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.troll.ambient"));
	public static final SoundEvent TROLL_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.troll.death"));
	public static final SoundEvent TROLL_GRABS_ROCK = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.troll.grab_rock"));
	public static final SoundEvent TROLL_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.troll.hurt"));
	public static final SoundEvent TROLL_THROWS_ROCK = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.troll.throw_rock"));
	public static final SoundEvent TWILIGHT_SCEPTER_HIT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.twilight_scepter.pearl_hit"));
	public static final SoundEvent TWILIGHT_SCEPTER_USE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.twilight_scepter.use"));
	public static final SoundEvent UNCRAFTING_TABLE_ACTIVATE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.uncrafting_table.activate"));
	public static final SoundEvent UNLOCK_VANISHING_BLOCK = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.vanish.unlock"));
	public static final SoundEvent UR_GHAST_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.ur_ghast.ambient"));
	public static final SoundEvent UR_GHAST_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.ur_ghast.death"));
	public static final SoundEvent UR_GHAST_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.ur_ghast.hurt"));
	public static final SoundEvent UR_GHAST_SHOOT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.ur_ghast.shoot"));
	public static final SoundEvent UR_GHAST_TANTRUM = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.ur_ghast.tantrum"));
	public static final SoundEvent UR_GHAST_WARN = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.ur_ghast.warn"));
	public static final SoundEvent VANISHING_BLOCK = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.vanish.vanish"));
	public static final SoundEvent WINTER_WOLF_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.winter_wolf.ambient"));
	public static final SoundEvent WINTER_WOLF_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.winter_wolf.death"));
	public static final SoundEvent WINTER_WOLF_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.winter_wolf.hurt"));
	public static final SoundEvent WINTER_WOLF_SHOOT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.winter_wolf.shoot"));
	public static final SoundEvent WINTER_WOLF_TARGET = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.winter_wolf.target"));
	public static final SoundEvent WOOD_SHIELD_SHATTERS = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.shield.shatter"));
	public static final SoundEvent WRAITH_AMBIENT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.wraith.ambient"));
	public static final SoundEvent WRAITH_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.wraith.death"));
	public static final SoundEvent WRAITH_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.wraith.hurt"));
	public static final SoundEvent WROUGHT_IRON_FENCE_EXTENDED = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.wrought_iron_fence.extend"));
	public static final SoundEvent YETI_DEATH = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.yeti.death"));
	public static final SoundEvent YETI_GRAB = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.yeti.grab"));
	public static final SoundEvent YETI_GROWL = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.yeti.growl"));
	public static final SoundEvent YETI_HURT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.yeti.hurt"));
	public static final SoundEvent YETI_THROW = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.yeti.throw"));
	public static final SoundEvent ZOMBIE_SCEPTER_USE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("item.twilightforest.zombie_scepter.use"));
	public static final SoundEvent OMINOUS_FIRE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.ominous_fire.light"));

	//Parrot sounds
	public static final SoundEvent ALPHA_YETI_PARROT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.parrot.imitate.alpha_yeti"));
	public static final SoundEvent CARMINITE_GOLEM_PARROT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.parrot.imitate.carminite_golem"));
	public static final SoundEvent DEATH_TOME_PARROT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.parrot.imitate.death_tome"));
	public static final SoundEvent HOSTILE_WOLF_PARROT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.parrot.imitate.hostile_wolf"));
	public static final SoundEvent HYDRA_PARROT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.parrot.imitate.hydra"));
	public static final SoundEvent ICE_CORE_PARROT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.parrot.imitate.ice_core"));
	public static final SoundEvent KOBOLD_PARROT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.parrot.imitate.kobold"));
	public static final SoundEvent MINOTAUR_PARROT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.parrot.imitate.minotaur"));
	public static final SoundEvent MOSQUITO_PARROT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.parrot.imitate.mosquito"));
	public static final SoundEvent NAGA_PARROT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.parrot.imitate.naga"));
	public static final SoundEvent REDCAP_PARROT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.parrot.imitate.redcap"));
	public static final SoundEvent WRAITH_PARROT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("entity.twilightforest.parrot.imitate.wraith"));

	public static final SoundEvent JAR_BREAK = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.jar.break"));
	public static final SoundEvent JAR_STEP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.jar.step"));
	public static final SoundEvent JAR_PLACE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.jar.place"));
	public static final SoundEvent JAR_HIT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.jar.hit"));
	public static final SoundEvent JAR_FALL = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.jar.fall"));

	public static final SoundEvent JAR_INSERT = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.jar.insert"));
	public static final SoundEvent JAR_REMOVE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.jar.remove"));
	public static final SoundEvent JAR_LID_SWAP = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.jar.lid_swap"));
	public static final SoundEvent JAR_WIGGLE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("block.twilightforest.jar.wiggle"));

	public static final SoundEvent MUSIC = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("music.twilightforest.twilight_forest"));

	public static final SoundEvent MUSIC_DISC_RADIANCE = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("music_disc.twilightforest.radiance"));
	public static final SoundEvent MUSIC_DISC_STEPS = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("music_disc.twilightforest.steps"));
	public static final SoundEvent MUSIC_DISC_SUPERSTITIOUS = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("music_disc.twilightforest.superstitious"));
	public static final SoundEvent MUSIC_DISC_HOME = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("music_disc.twilightforest.home"));
	public static final SoundEvent MUSIC_DISC_WAYFARER = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("music_disc.twilightforest.wayfarer"));
	public static final SoundEvent MUSIC_DISC_FINDINGS = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("music_disc.twilightforest.findings"));
	public static final SoundEvent MUSIC_DISC_MAKER = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("music_disc.twilightforest.maker"));
	public static final SoundEvent MUSIC_DISC_THREAD = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("music_disc.twilightforest.thread"));
	public static final SoundEvent MUSIC_DISC_MOTION = SoundEvent.createVariableRangeEvent(TwilightForestMod.prefix("music_disc.twilightforest.motion"));

	public static void init() {
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("environment.twilightforest.acid_rain"), ACID_RAIN_BURNS);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.alpha_yeti.alert"), ALPHA_YETI_ALERT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.alpha_yeti.death"), ALPHA_YETI_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.alpha_yeti.grab"), ALPHA_YETI_GRAB);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.alpha_yeti.growl"), ALPHA_YETI_GROWL);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.alpha_yeti.hurt"), ALPHA_YETI_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.alpha_yeti.ice"), ALPHA_YETI_ICE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.alpha_yeti.pant"), ALPHA_YETI_PANT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.alpha_yeti.roar"), ALPHA_YETI_ROAR);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.alpha_yeti.throw"), ALPHA_YETI_THROW);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.beanstalk.grow"), BEANSTALK_GROWTH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.bighorn_sheep.ambient"), BIGHORN_SHEEP_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.bighorn_sheep.death"), BIGHORN_SHEEP_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.bighorn_sheep.hurt"), BIGHORN_SHEEP_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.bighorn_sheep.step"), BIGHORN_SHEEP_STEP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.blockchain_goblin.ambient"), BLOCKCHAIN_GOBLIN_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.blockchain_goblin.death"), BLOCKCHAIN_GOBLIN_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.blockchain_goblin.hurt"), BLOCKCHAIN_GOBLIN_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.block_and_chain.collide"), BLOCK_AND_CHAIN_COLLIDE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.block_and_chain.fire"), BLOCK_AND_CHAIN_FIRED);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.block_and_chain.hit"), BLOCK_AND_CHAIN_HIT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.generic.annihilation"), BLOCK_ANNIHILATED);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.boar.ambient"), BOAR_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.boar.death"), BOAR_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.boar.hurt"), BOAR_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.boar.step"), BOAR_STEP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.chiseled_bookshelf.convert"), BOOKSHELF_CONVERTS);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.boss_chest.appear"), BOSS_CHEST_APPEAR);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.flask.break"), BRITTLE_FLASK_BREAK);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.flask.crack"), BRITTLE_FLASK_CRACK);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.bug.squish"), BUG_SQUISH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.builder.create"), BUILDER_CREATE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.builder.off"), BUILDER_OFF);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.builder.on"), BUILDER_ON);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.builder.replace"), BUILDER_REPLACE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.candelabra.light"), CANDELABRA_LIGHT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.candelabra.ominous"), CANDELABRA_OMINOUS);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.carminite_broodling.ambient"), CARMINITE_BROODLING_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.carminite_broodling.death"), CARMINITE_BROODLING_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.carminite_broodling.hurt"), CARMINITE_BROODLING_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.carminite_broodling.step"), CARMINITE_BROODLING_STEP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.carminite_ghastguard.ambient"), CARMINITE_GHASTGUARD_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.carminite_ghastguard.death"), CARMINITE_GHASTGUARD_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.carminite_ghastguard.hurt"), CARMINITE_GHASTGUARD_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.carminite_ghastguard.shoot"), CARMINITE_GHASTGUARD_SHOOT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.carminite_ghastguard.warn"), CARMINITE_GHASTGUARD_WARN);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.carminite_ghastling.ambient"), CARMINITE_GHASTLING_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.carminite_ghastling.death"), CARMINITE_GHASTLING_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.carminite_ghastling.hurt"), CARMINITE_GHASTLING_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.carminite_ghastling.shoot"), CARMINITE_GHASTLING_SHOOT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.carminite_ghastling.warn"), CARMINITE_GHASTLING_WARN);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.carminite_golem.attack"), CARMINITE_GOLEM_ATTACK);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.carminite_golem.death"), CARMINITE_GOLEM_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.carminite_golem.hurt"), CARMINITE_GOLEM_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.carminite_golem.step"), CARMINITE_GOLEM_STEP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.casket.close"), CASKET_CLOSE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.casket.locked"), CASKET_LOCKED);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.casket.open"), CASKET_OPEN);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.casket.repair"), CASKET_REPAIR);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.charm.keep"), CHARM_KEEP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.charm.life"), CHARM_LIFE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.cicada"), CICADA);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.travellers_gear.cycle_maps"), CYCLE_MAPS);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.travellers_gear.cycle_maps_empty"), CYCLE_MAPS_EMPTY);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.death_tome.ambient"), DEATH_TOME_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.death_tome.death"), DEATH_TOME_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.death_tome.hurt"), DEATH_TOME_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.deer.ambient"), DEER_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.deer.death"), DEER_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.deer.hurt"), DEER_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.deer.eat"), DEER_EAT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.door.activate"), DOOR_ACTIVATED);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.door.reappear"), DOOR_REAPPEAR);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.door.vanish"), DOOR_VANISH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.travellers_gear.double_jump"), DOUBLE_JUMP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.drying_rack.add_item"), DRYING_RACK_ADD_ITEM);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.drying_rack.remove_item"), DRYING_RACK_REMOVE_ITEM);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.dwarf_rabbit.ambient"), DWARF_RABBIT_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.dwarf_rabbit.death"), DWARF_RABBIT_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.dwarf_rabbit.hurt"), DWARF_RABBIT_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.fan.whoosh"), FAN_WHOOSH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.fire_beetle.ambient"), FIRE_BEETLE_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.fire_beetle.death"), FIRE_BEETLE_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.fire_beetle.hurt"), FIRE_BEETLE_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.fire_beetle.shoot"), FIRE_BEETLE_SHOOT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.fire_beetle.step"), FIRE_BEETLE_STEP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.flask.fill"), FLASK_FILL);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.ghast_trap.active"), GHAST_TRAP_ACTIVE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.ghast_trap.ambient"), GHAST_TRAP_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.ghast_trap.on"), GHAST_TRAP_ON);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.ghast_trap.spindown"), GHAST_TRAP_SPINDOWN);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.ghast_trap.warmup"), GHAST_TRAP_WARMUP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.glass_sword.break"), GLASS_SWORD_BREAK);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.goblin_knight.ambient"), GOBLIN_KNIGHT_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.goblin_knight.death"), GOBLIN_KNIGHT_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.goblin_knight.hurt"), GOBLIN_KNIGHT_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.goblin_knight.muffled.ambient"), GOBLIN_KNIGHT_MUFFLED_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.goblin_knight.muffled.death"), GOBLIN_KNIGHT_MUFFLED_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.goblin_knight.muffled.hurt"), GOBLIN_KNIGHT_MUFFLED_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.travellers_goggles.zoom_in"), GOGGLES_ZOOM_IN);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.travellers_goggles.zoom_out"), GOGGLES_ZOOM_OUT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.hedge_spider.ambient"), HEDGE_SPIDER_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.hedge_spider.death"), HEDGE_SPIDER_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.hedge_spider.hurt"), HEDGE_SPIDER_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.hedge_spider.step"), HEDGE_SPIDER_STEP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.helmet_crab.ambient"), HELMET_CRAB_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.helmet_crab.death"), HELMET_CRAB_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.helmet_crab.hurt"), HELMET_CRAB_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.helmet_crab.step"), HELMET_CRAB_STEP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.hostile_wolf.ambient"), HOSTILE_WOLF_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.hostile_wolf.death"), HOSTILE_WOLF_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.hostile_wolf.hurt"), HOSTILE_WOLF_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.hostile_wolf.target"), HOSTILE_WOLF_TARGET);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.hydra.death"), HYDRA_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.hydra.growl"), HYDRA_GROWL);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.hydra.hurt"), HYDRA_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.hydra.roar"), HYDRA_ROAR);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.hydra.shoot"), HYDRA_SHOOT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.hydra.shoot_fire"), HYDRA_SHOOT_FIRE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.hydra.warn"), HYDRA_WARN);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.ice_bomb.fired"), ICE_BOMB_FIRED);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.ice.ambient"), ICE_CORE_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.ice.death"), ICE_CORE_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.ice.hurt"), ICE_CORE_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.ice.shoot"), ICE_CORE_SHOOT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.jet.active"), JET_ACTIVE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.jet.pop"), JET_POP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.jet.start"), JET_START);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.king_spider.ambient"), KING_SPIDER_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.king_spider.death"), KING_SPIDER_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.king_spider.hurt"), KING_SPIDER_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.king_spider.step"), KING_SPIDER_STEP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.knightmetal_armor.equip"), KNIGHTMETAL_EQUIP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.knight_phantom.ambient"), KNIGHT_PHANTOM_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.knight_phantom.death"), KNIGHT_PHANTOM_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.knight_phantom.hurt"), KNIGHT_PHANTOM_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.knight_phantom.axe"), KNIGHT_PHANTOM_THROW_AXE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.knight_phantom.pickaxe"), KNIGHT_PHANTOM_THROW_PICK);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.kobold.ambient"), KOBOLD_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.kobold.death"), KOBOLD_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.kobold.hurt"), KOBOLD_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.kobold.munch"), KOBOLD_MUNCH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.lamp.burn"), LAMP_BURN);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.lich.ambient"), LICH_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.lich_clone.hurt"), LICH_CLONE_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.lich.death"), LICH_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.lich.hurt"), LICH_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.lich.pop_mob"), LICH_POP_MOB);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.lich.shoot"), LICH_SHOOT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.lich.teleport"), LICH_TELEPORT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.life_scepter.drain"), LIFE_SCEPTER_DRAIN);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.vanish.locked"), LOCKED_VANISHING_BLOCK);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.loyal_zombie.ambient"), LOYAL_ZOMBIE_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.loyal_zombie.death"), LOYAL_ZOMBIE_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.loyal_zombie.hurt"), LOYAL_ZOMBIE_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.loyal_zombie.step"), LOYAL_ZOMBIE_STEP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.magnet.grab"), MAGNET_GRAB);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.maze_slime.death"), MAZE_SLIME_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.maze_slime_small.death"), MAZE_SLIME_DEATH_SMALL);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.maze_slime.hurt"), MAZE_SLIME_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.maze_slime_small.hurt"), MAZE_SLIME_HURT_SMALL);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.maze_slime.squish"), MAZE_SLIME_SQUISH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.maze_slime_small.squish"), MAZE_SLIME_SQUISH_SMALL);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.knightmetal_shield.shatter"), METAL_SHIELD_SHATTERS);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.minion.ambient"), MINION_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.minion.death"), MINION_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.minion.hurt"), MINION_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.minion.step"), MINION_STEP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.minion.summon"), MINION_SUMMON);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.minoshroom.ambient"), MINOSHROOM_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.minoshroom.attack"), MINOSHROOM_ATTACK);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.minoshroom.death"), MINOSHROOM_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.minoshroom.hurt"), MINOSHROOM_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.minoshroom.slam"), MINOSHROOM_SLAM);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.minoshroom.step"), MINOSHROOM_STEP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.minotaur.ambient"), MINOTAUR_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.minotaur.attack"), MINOTAUR_ATTACK);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.minotaur.death"), MINOTAUR_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.minotaur.hurt"), MINOTAUR_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.minotaur.step"), MINOTAUR_STEP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.mist_wolf.ambient"), MIST_WOLF_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.mist_wolf.death"), MIST_WOLF_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.mist_wolf.hurt"), MIST_WOLF_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.mist_wolf.target"), MIST_WOLF_TARGET);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.moonworm.squish"), MOONWORM_SQUISH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.mosquito.ambient"), MOSQUITO);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.naga.hiss"), NAGA_HISS);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.naga.hurt"), NAGA_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.naga.rattle"), NAGA_RATTLE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.ore_meter.clear"), ORE_METER_CLEAR);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.ore_meter.crackle"), ORE_METER_CRACKLE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.ore_meter.target_block"), ORE_METER_TARGET_BLOCK);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.trophy_pedestal.activate"), PEDESTAL_ACTIVATE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.penguin.ambient"), PENGUIN_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.penguin.death"), PENGUIN_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.penguin.hurt"), PENGUIN_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.travellers_gear.perfect_dodge"), PERFECT_DODGE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.torchberry.harvest"), PICKED_TORCHBERRIES);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.pinch_beetle.ambient"), PINCH_BEETLE_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.pinch_beetle.attack"), PINCH_BEETLE_ATTACK);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.pinch_beetle.death"), PINCH_BEETLE_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.pinch_beetle.hurt"), PINCH_BEETLE_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.pinch_beetle.step"), PINCH_BEETLE_STEP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.portal.whoosh"), PORTAL_WHOOSH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.transformation_powder.use"), POWDER_USE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.quest_ram.ambient"), QUEST_RAM_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.quest_ram.death"), QUEST_RAM_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.quest_ram.hurt"), QUEST_RAM_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.quest_ram.step"), QUEST_RAM_STEP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.raven.caw"), RAVEN_CAW);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.raven.squawk"), RAVEN_SQUAWK);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.reactor.ambient"), REACTOR_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.reappearing_block.reappear"), REAPPEAR_BLOCK);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.reappearing_block.vanish"), REAPPEAR_POOF);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.redcap.ambient"), REDCAP_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.redcap.death"), REDCAP_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.redcap.hurt"), REDCAP_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.fortification_shield.add"), SHIELD_ADD);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.fortification_shield.block"), SHIELD_BLOCK);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.fortification_shield.break"), SHIELD_BREAK);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.fortification_shield.expire"), SHIELD_EXPIRE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.travellers_gear.side_step"), SIDE_STEP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.travellers_gear.side_step_ready"), SIDE_STEP_CHARGED);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.skeleton_druid.ambient"), SKELETON_DRUID_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.skeleton_druid.death"), SKELETON_DRUID_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.skeleton_druid.hurt"), SKELETON_DRUID_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.skeleton_druid.shoot"), SKELETON_DRUID_SHOOT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.skeleton_druid.step"), SKELETON_DRUID_STEP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.skull_chest.close"), SKULL_CHEST_CLOSE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.skull_chest.locked"), SKULL_CHEST_LOCKED);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.skull_chest.open"), SKULL_CHEST_OPEN);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.slider.move"), SLIDER);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.slime_beetle.ambient"), SLIME_BEETLE_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.slime_beetle.death"), SLIME_BEETLE_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.slime_beetle.hurt"), SLIME_BEETLE_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.slime_beetle.squish"), SLIME_BEETLE_SQUISH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.slime_beetle.step"), SLIME_BEETLE_STEP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.smoker.start"), SMOKER_START);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.snow_guardian.ambient"), SNOW_GUARDIAN_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.snow_guardian.death"), SNOW_GUARDIAN_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.snow_guardian.hurt"), SNOW_GUARDIAN_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.snow_queen.ambient"), SNOW_QUEEN_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.snow_queen.attack"), SNOW_QUEEN_ATTACK);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.snow_queen.break"), SNOW_QUEEN_BREAK);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.snow_queen.death"), SNOW_QUEEN_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.snow_queen.hurt"), SNOW_QUEEN_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.squirrel.ambient"), SQUIRREL_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.squirrel.death"), SQUIRREL_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.squirrel.hurt"), SQUIRREL_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.travellers_gear.swap_hotbar"), SWAP_HOTBAR);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.swarm_spider.ambient"), SWARM_SPIDER_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.swarm_spider.death"), SWARM_SPIDER_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.swarm_spider.hurt"), SWARM_SPIDER_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.swarm_spider.step"), SWARM_SPIDER_STEP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.tear.break"), TEAR_BREAK);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.core.time"), TIME_CORE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.tiny_bird.chirp"), TINY_BIRD_CHIRP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.tiny_bird.hurt"), TINY_BIRD_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.tiny_bird.song"), TINY_BIRD_SONG);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.tiny_bird.takeoff"), TINY_BIRD_TAKEOFF);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.towerwood_borer.ambient"), TOWERWOOD_BORER_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.towerwood_borer.death"), TOWERWOOD_BORER_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.towerwood_borer.hurt"), TOWERWOOD_BORER_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.towerwood_borer.step"), TOWERWOOD_BORER_STEP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.core.transformation"), TRANSFORMATION_CORE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.troll.ambient"), TROLL_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.troll.death"), TROLL_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.troll.grab_rock"), TROLL_GRABS_ROCK);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.troll.hurt"), TROLL_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.troll.throw_rock"), TROLL_THROWS_ROCK);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.twilight_scepter.pearl_hit"), TWILIGHT_SCEPTER_HIT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.twilight_scepter.use"), TWILIGHT_SCEPTER_USE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.uncrafting_table.activate"), UNCRAFTING_TABLE_ACTIVATE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.vanish.unlock"), UNLOCK_VANISHING_BLOCK);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.ur_ghast.ambient"), UR_GHAST_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.ur_ghast.death"), UR_GHAST_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.ur_ghast.hurt"), UR_GHAST_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.ur_ghast.shoot"), UR_GHAST_SHOOT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.ur_ghast.tantrum"), UR_GHAST_TANTRUM);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.ur_ghast.warn"), UR_GHAST_WARN);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.vanish.vanish"), VANISHING_BLOCK);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.winter_wolf.ambient"), WINTER_WOLF_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.winter_wolf.death"), WINTER_WOLF_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.winter_wolf.hurt"), WINTER_WOLF_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.winter_wolf.shoot"), WINTER_WOLF_SHOOT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.winter_wolf.target"), WINTER_WOLF_TARGET);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.shield.shatter"), WOOD_SHIELD_SHATTERS);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.wraith.ambient"), WRAITH_AMBIENT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.wraith.death"), WRAITH_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.wraith.hurt"), WRAITH_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.wrought_iron_fence.extend"), WROUGHT_IRON_FENCE_EXTENDED);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.yeti.death"), YETI_DEATH);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.yeti.grab"), YETI_GRAB);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.yeti.growl"), YETI_GROWL);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.yeti.hurt"), YETI_HURT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.yeti.throw"), YETI_THROW);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("item.twilightforest.zombie_scepter.use"), ZOMBIE_SCEPTER_USE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.ominous_fire.light"), OMINOUS_FIRE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.parrot.imitate.alpha_yeti"), ALPHA_YETI_PARROT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.parrot.imitate.carminite_golem"), CARMINITE_GOLEM_PARROT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.parrot.imitate.death_tome"), DEATH_TOME_PARROT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.parrot.imitate.hostile_wolf"), HOSTILE_WOLF_PARROT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.parrot.imitate.hydra"), HYDRA_PARROT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.parrot.imitate.ice_core"), ICE_CORE_PARROT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.parrot.imitate.kobold"), KOBOLD_PARROT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.parrot.imitate.minotaur"), MINOTAUR_PARROT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.parrot.imitate.mosquito"), MOSQUITO_PARROT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.parrot.imitate.naga"), NAGA_PARROT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.parrot.imitate.redcap"), REDCAP_PARROT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("entity.twilightforest.parrot.imitate.wraith"), WRAITH_PARROT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.jar.break"), JAR_BREAK);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.jar.step"), JAR_STEP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.jar.place"), JAR_PLACE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.jar.hit"), JAR_HIT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.jar.fall"), JAR_FALL);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.jar.insert"), JAR_INSERT);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.jar.remove"), JAR_REMOVE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.jar.lid_swap"), JAR_LID_SWAP);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("block.twilightforest.jar.wiggle"), JAR_WIGGLE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("music.twilightforest.twilight_forest"), MUSIC);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("music_disc.twilightforest.radiance"), MUSIC_DISC_RADIANCE);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("music_disc.twilightforest.steps"), MUSIC_DISC_STEPS);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("music_disc.twilightforest.superstitious"), MUSIC_DISC_SUPERSTITIOUS);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("music_disc.twilightforest.home"), MUSIC_DISC_HOME);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("music_disc.twilightforest.wayfarer"), MUSIC_DISC_WAYFARER);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("music_disc.twilightforest.findings"), MUSIC_DISC_FINDINGS);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("music_disc.twilightforest.maker"), MUSIC_DISC_MAKER);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("music_disc.twilightforest.thread"), MUSIC_DISC_THREAD);
		Registry.register(BuiltInRegistries.SOUND_EVENT, TwilightForestMod.prefix("music_disc.twilightforest.motion"), MUSIC_DISC_MOTION);
	}

}
